name: Foundations Starter Project

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: ' 3.8.5'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # just in case they are missing from requirements.txt
        pip install flake8 pytest  
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --doctest-modules --junitxml=junit/test-results.xml
    - name: Preparing database for deployment 
      run: | 
        echo "  DB_PASSWORD: \"${{ secrets.DB_PASSWORD }}\" " >> app.yaml
        echo "  DB_USER: \"${{ secrets.DB_USER }}\" " >> app.yaml
        echo "  DB_HOST: \"${{ secrets.DB_HOST }}\" " >> app.yaml
        echo "  SECRET_KEY: \"${{ secrets.SECRET_KEY }}\" " >> app.yaml
        echo "  DB_URI: \"${{ secrets.DB_URI }}\" " >> app.yaml
        more app.yaml
    - name: Preparing Mail Server 
      run: | 
        echo "  MAIL_PASSWORD: \"${{ secrets.MAIL_PASSWORD }}\" " >> app.yaml
        echo "  MAIL_SERVER: \"${{ secrets.MAIL_SERVER }}\" " >> app.yaml
        echo "  MAIL_USER: \"${{ secrets.MAIL_USER }}\" " >> app.yaml
        more app.yaml
    - name: Deploy to Google App Engine
      uses: google-github-actions/deploy-appengine@main
      with:
        credentials: ${{ secrets.CEBJJ_KEY }}
    - name: Cleanup Old Versions on Google App Engine 
      run: gcloud app versions delete --quiet `gcloud app versions list --format="value(id)[terminator=' ']" --filter="traffic_split=0"`